---
# tasks file for webserver
- name: "install httpd"
  package:
    name: "httpd"
    state: present
- name: "run the script"
  shell: echo "<h1>HELLO MUSTAFA Welcome YOU ARE CONNECTED TO $(hostname -f)</h1>" > /var/www/html/index.html
    
- name: "restart httpd"
  service:
    name: "httpd"
    state: started
